Medicine2/Medicine/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Runtime.Remoting.Contexts;
using System.Security.Cryptography;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using BE;
using BL;
using Medicine.Models;

namespace Medicine.Controllers
{
    public class AdminController : Controller
    {

        // GET: Admin
        public ActionResult Index()
        {
            return View();
        }
        
        [HttpPost]
        public ActionResult LogIn(FormCollection collection)
        {
            try
            {
                Passwordmodel passwordmodel = new Passwordmodel();
                passwordmodel.CheckAdminPassword(int.Parse(collection["IdAdmin"]), collection["PassName"]);
                if (passwordmodel.CheckAdminPassword(int.Parse(collection["IdAdmin"]), collection["PassName"]))
                {
                   
                    return RedirectToAction("AdminOps");
                }
            }
            catch(Exception e)
            {
                 
                Response.Write("<script language=javascript>alert('"+e.Message+"');</script>");
                return View("index");
            }
            return RedirectToAction("Error");
        }
        public ActionResult AdminOps()
        {
            return View();
        }
        public ActionResult Error()
        {
            return View();
        } 
    
        public ActionResult AddPatient()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddPatient(FormCollection collection)
        {
            try
            {
                Patient p = new Patient() { FirstName = collection["FirstName"], LastName = collection["LastName"], Id = int.Parse(collection["Id"]), Address = collection["Address"], dateOfBirth = DateTime.Parse(collection["dateOfBirth"]) };
                PatientModel model = new PatientModel();
                model.AddPatient(p);
                return RedirectToAction("AdminOps");
            }
            catch (Exception e)
            {
                Response.Write("<script language=javascript>alert('"+e.Message+"');</script>");
                return View("AddPatient");
            }
        }

        public ActionResult AddDoctor()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddDoctor(FormCollection collection)
        {
            try
            {
                Doctor d = new Doctor() { FirstName = collection["FirstName"], LastName = collection["LastName"], Id = int.Parse(collection["Id"]), LicenseNumber = collection["LicenseNumber"], Address = collection["Address"], dateOfBirth = DateTime.Parse(collection["dateOfBirth"]) };
                DoctorModel model = new DoctorModel();
                model.AddDoctor(d);
                Passwordmodel passwordmodel = new Passwordmodel();
                UserPassword user = new UserPassword() { Id = int.Parse(collection["Id"]), Password = collection["DoctorPassword"] };
                passwordmodel.AddPassword(user);
            }
            catch (Exception e)
            {

                Response.Write("<script language=javascript>alert('"+e.Message+"');</script>");
                return View("AddDoctor");
            }
            return RedirectToAction("AdminOps");
        }
        public ActionResult viewDoctors()
        {
            DoctorModel model = new DoctorModel();
            return View(model.GetDoctors());
        }
        public ActionResult EditDoctor(int id)
        {
            DoctorModel model = new DoctorModel();
            Doctor d = model.GetDoctor(id);
            return View(d);
        }
        [HttpPost]
        public ActionResult EditDoctor(int id, FormCollection collection)
        {
            DoctorModel model = new DoctorModel();

            Doctor d = new Doctor() { FirstName = collection["FirstName"], LastName = collection["LastName"], LicenseNumber = collection["LicenseNumber"], Id = id, Address = collection["Address"], dateOfBirth = DateTime.Parse(collection["dateOfBirth"]) };
            model.EditDoctor( d);
            return RedirectToAction("viewDoctors");
        }

        public ActionResult viewPatients()
        {
            PatientModel model = new PatientModel();

            return View(model.GetPatients());
        }
        public ActionResult EditPatient(int id)
        {
            PatientModel model = new PatientModel();
            Patient p = model.GetPatient(id);
            return View(p);
        }
        [HttpPost]
        public ActionResult EditPatient(int id, FormCollection collection)
        {
            PatientModel model = new PatientModel();
            Patient p = new Patient() { FirstName = collection["FirstName"], LastName = collection["LastName"], Id = id, Address = collection["Address"], dateOfBirth = DateTime.Parse(collection["dateOfBirth"]) };
            model.EditPatient(p);
            return RedirectToAction("viewPatients");
        }

        public ActionResult DrugData(Drug d)
        {
            DrugCatalogModel model = new DrugCatalogModel();
            DrugDataModel dataModel = new DrugDataModel() { DrugName = d.Name, Values = model.GetDrugUse(d.NDC) };
            return View(dataModel);
        }

        public ActionResult updateCatalog()
        {
            DrugCatalogModel catalogModel = new DrugCatalogModel();
            List<Drug> ld = catalogModel.GetDrugs();   
             return View(ld);
        }

        public ActionResult UpdateImage(String NDC)
        {
            return View(model:NDC);


        }
        [HttpPost]
        public ActionResult UpdateImage(FormCollection collection, HttpPostedFileBase file)
        {
            try
            {
                //  string filefullpath = Path.GetFullPath(file.FileName);
                // extract only the fielname
                var fileName = Path.GetFileName(file.FileName);
                // store the file inside ~/App_Data/uploads folder
                string path = @"\GoogleDriveFiles\" + fileName;
                DrugCatalogModel catalogModel = new DrugCatalogModel();
                catalogModel.UpdateImage(collection["NDC"], file, path);
            }
            catch (Exception e)
            {

                Response.Write("<script language=javascript>alert('"+e.Message+"');</script>");
                return View("UpdateImage");
            }
            Response.Write(@"<script language='javascript'>alert('התמונה עודכנה בהצלחה');</script>");
            return View("AdminOps");

        }
        public ActionResult DeleteDrug(string NDC)
        {
            DrugCatalogModel model = new DrugCatalogModel();
            model.deleteDrug(NDC);
            return RedirectToAction("updateCatalog");
        }


        public ActionResult getDrugFromAdmin()
        {
            return View();
        }
        [HttpPost]
        public ActionResult getDrugFromAdmin(FormCollection collection)
        {
            DrugCatalogModel model = new DrugCatalogModel();
            Drug d = model.GetDrugByName(collection["drug"]);
            return RedirectToAction("DrugData", d);
        }
        public ActionResult CreateDrug()
        {
            return View();
        }
        [HttpPost]
        public ActionResult CreateDrug(FormCollection collection)
        {
            try
            {
                DrugCatalogModel model = new DrugCatalogModel();  
                var image = @"\GoogleDriveFiles\" + collection["Img"];
                Drug dr = new Drug() { Name = collection["Name"], ManufacturerName = collection["ManufacturerName"], ActiveIngredientUnit = collection["ActiveIngredientUnit"], GenericName = collection["GenericName"], ImagePath = image, NDC = collection["NDC"] };
                model.AddDrug(dr); 
                return RedirectToAction("updateCatalog");

            }
            catch (Exception e)
            {
                Response.Write("<script language=javascript>alert('"+e.Message +"');</script>");
                return View("CreateDrug");
            }
            
        }

        public ActionResult ExeptionHandler(string s)
        {
            ExeptionHandler model = new ExeptionHandler() { Message = s };
            return View(model);
        }
    }
}

Medicine2/Medicine/Controllers/CatalogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BE;
using Medicine.Models;

namespace Medicine.Controllers
{
    public class CatalogController : Controller
    {
        // GET: DrugCatalog
        public ActionResult Index()
        {
            DrugCatalogModel model = new DrugCatalogModel();

            return View(model.GetDrugs());
        }

        
    }
}

Medicine2/Medicine/Controllers/PatientController.cs
using BE;
using BL;
using Medicine.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Medicine.Controllers
{
    public class PatientController : Controller
    {
        // GET: Patient
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(string idp)
        {
            try
            {
                PatientModel patientModel = new PatientModel() { PatientId = int.Parse(idp)};
                Patient p = patientModel.GetPatient(int.Parse(idp));
                return View("IndexPo", patientModel);
            }
            catch (Exception e)
            {
                Response.Write("<script language=javascript>alert('" + e.Message + "');</script>");
                return View("Index");
            }

        }
         
        public ActionResult Prescription(int id)
        {
            try
            {
                PatientBL BL = new PatientBL();
                List<Prescription> l = BL.GetPatientPrescription(id);
                return View(l);
            }
            catch (Exception e)
            {
                Response.Write("<script language=javascript>alert('" + e.Message + "');</script>");
                return View("IndexPo");
            }

        }

    }
}

Medicine2/Medicine/Views/Patient/IndexPo.cshtml
@model PatientModel
    @using Medicine.Models
@{
    var item = Model;
}

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />

    <title>מטופל</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="CareMed demo project">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="/styles/bootstrap4/bootstrap.min.css">
    <link href="/plugins/font-awesome-4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="/plugins/OwlCarousel2-2.2.1/owl.carousel.css">
    <link rel="stylesheet" type="text/css" href="/plugins/OwlCarousel2-2.2.1/owl.theme.default.css">
    <link rel="stylesheet" type="text/css" href="/plugins/OwlCarousel2-2.2.1/animate.css">
    <link rel="stylesheet" type="text/css" href="/styles/about.css">
    <link rel="stylesheet" type="text/css" href="/styles/about_responsive.css">
</head>
<body>
    <div class="super_container">

        <!-- Header -->

        <header class="header trans_200">

            <!-- Top Bar -->
            <div class="top_bar">
                <div class="container">
                    <div class="row">
                        <div class="col">
                            <div class="top_bar_content d-flex flex-row align-items-center justify-content-start">
                                <div class="emergencies  d-flex flex-row align-items-center justify-content-start ml-auto">למקרי חירום: 035467890</div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>

            <!-- Header Content -->
            <div class="header_container">
                <div class="container">
                    <div class="row">
                        <div class="col">
                            <div class="header_content d-flex flex-row align-items-center justify-content-start">
                                <nav class="main_nav ml-auto">
                                    <ul>
                                       
                                        <li>@Html.ActionLink("קטלוג תרופות", "Index", "Catalog")</li>
                                        <li>@Html.ActionLink("מטופל", "Index", "Patient") </li>
                                        <li>@Html.ActionLink("רופא", "Index", "Doctor")</li>
                                        <li>@Html.ActionLink("מנהל", "Index", "Admin")</li>
                                        <li>@Html.ActionLink("בית", "Index", "Home")</li>

                                    </ul>
                                </nav>
                                <div class="hamburger ml-auto"><i class="fa fa-bars" aria-hidden="true"></i></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>



             

                <!-- Logo -->
                <div class="logo_container_outer">
                    <div class="container">
                        <div class="row">
                            <div class="col">
                                <div class="logo_container">
                                    <a href="#">
                                        <div class="logo_content d-flex flex-column align-items-start justify-content-center">
                                            <div class="logo_line"></div>
                                            <div class="logo d-flex flex-row align-items-center justify-content-center">
                                                <div class="logo_text">Care<span>Med</span></div>
                                                <div class="logo_box">+</div>
                                            </div>
                                            <div class="logo_sub">Health Care Center</div>
                                        </div>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </header>





        <!-- Menu -->

        <div class="menu_container menu_mm">

            <!-- Menu Close Button -->
            <div class="menu_close_container">
                <div class="menu_close"></div>
            </div>

           
        </div>

        <!-- Home -->

        <div class="home">
            <div class="home_background parallax-window" data-parallax="scroll" data-image-src="/images/about.jpg" data-speed="0.8"></div>
            <div class="home_container">
                <div class="container">
                    <div class="row">
                        <div class="col">
                            <div class="home_content">
                                <div class="home_title"> <span>מטופל - אזור אישי</span></div>
                                <div class="breadcrumbs">
                                    <ul>
                                        <li><a href="#">בית</a></li>
                                        <li>מטופל</li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- About -->
        <div class="about">
            <div class="container">
                <div class="row">
                    About Content
                    <div class="col-lg-8">
                        <div class="section_title" dir="rtl"><h2>לשירותך...</h2></div>
                        

                        <div class="button about_button" align="center">@Html.ActionLink("צפייה במרשמים שלך", "Prescription" ,new { id = item.PatientId })</div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</body>
</html>

Medicine2/Medicine/Views/Patient/IndexPrec.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>IndexPrec</title>
</head>
<body>
    <div> 
    </div>
</body>
</html>

Medicine2/Medicine/Views/Patient/Prescription.cshtml
@model IEnumerable<BE.Prescription>
    @using Medicine.Models
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>מנהל</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="CareMed demo project">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="/styles/bootstrap4/bootstrap.min.css">
    <link href="/plugins/font-awesome-4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="/plugins/OwlCarousel2-2.2.1/owl.carousel.css">
    <link rel="stylesheet" type="text/css" href="/plugins/OwlCarousel2-2.2.1/owl.theme.default.css">
    <link rel="stylesheet" type="text/css" href="/plugins/OwlCarousel2-2.2.1/animate.css">
    <link rel="stylesheet" type="text/css" href="~/styles/admin.css">
    <link rel="stylesheet" type="text/css" href="~/styles/admin_responsive.css">
</head>
<body>

    <div class="super_container">

        <style>
            .bordered {
                width: 1200px;
                height: 300px;
                padding: 20px;
                border: 5px ridge black;
            }
        </style>



        <!-- Header -->

        <header class="header trans_200">

            <!-- Top Bar -->
            <div class="top_bar">
                <div class="container">
                    <div class="row">
                        <div class="col">
                            <div class="top_bar_content d-flex flex-row align-items-center justify-content-start">
                                <div class="emergencies  d-flex flex-row align-items-center justify-content-start ml-auto">למקרי חירום: 035467890</div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>

            <!-- Header Content -->
            <div class="header_container">
                <div class="container">
                    <div class="row">
                        <div class="col">
                            <div class="header_content d-flex flex-row align-items-center justify-content-start">
                                <nav class="main_nav ml-auto">
                                    <ul>
                                        <li>@Html.ActionLink("קטלוג תרופות", "Index", "Catalog")</li>
                                        <li>@Html.ActionLink("מטופל", "Index", "Patient") </li>
                                        <li>@Html.ActionLink("רופא", "Index", "Doctor")</li>
                                        <li>@Html.ActionLink("מנהל", "Index", "Admin")</li>
                                        <li>@Html.ActionLink("בית", "Index", "Home")</li>
                                    </ul>
                                </nav>
                                <div class="hamburger ml-auto"><i class="fa fa-bars" aria-hidden="true"></i></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>



            <!-- Logo -->
            <div class="logo_container_outer">
                <div class="container">
                    <div class="row">
                        <div class="col">
                            <div class="logo_container">
                                <a href="#">
                                    <div class="logo_content d-flex flex-column align-items-start justify-content-center">
                                        <div class="logo_line"></div>
                                        <div class="logo d-flex flex-row align-items-center justify-content-center">
                                            <div class="logo_text">Care<span>Med</span></div>
                                            <div class="logo_box">+</div>
                                        </div>
                                        <div class="logo_sub">Health Care Center</div>
                                    </div>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </header>




        <!-- Home -->

        <div class="home">
            <div class="home_background parallax-window" data-parallax="scroll" data-image-src="/images/services.jpg" data-speed="0.8"></div>
            <div class="home_container">
                <div class="container">
                    <div class="row">
                        <div class="col">
                            <div class="home_content">
                                <div class="home_title"><span>המרשמים שלך - איזור אישי</span></div>
                                <div class="breadcrumbs">
                                    <ul>
                                        <li><a href="#">בית</a></li>
                                        <li>מנהל</li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Services -->
       
        <div align="center">
            @foreach (var item in Model)
            {
                <br />
                <div class="bordered" dir="rtl" align="right">
                    @{string StartDate = "תאריך הנפקת המרשם: " + item.StartDate.ToShortDateString();
                        string EndDate = "תאריך תפוגת צריכת התרופה: " + item.EndDate.ToShortDateString();
                        PatientModel patientmodel = new PatientModel();
                        BE.Patient p = patientmodel.GetPatient(item.PatientId);
                        string FirstName = "שם פרטי: " + p.FirstName;
                        string LastName = "שם משפחה: " + p.LastName;
                        string idcust = "מספר תעודת זהות: " + p.Id;
                        DoctorModel doctormodel = new DoctorModel();
                        BE.Doctor doctor = doctormodel.GetDoctor(item.DoctorId);
                        string docname = "שם רופא מטפל:דוקטור " + doctor.FirstName + " " + doctor.LastName;
                        DrugCatalogModel drugData = new DrugCatalogModel();
                        BE.Drug d = drugData.GetDrug(item.DrugNDC);
                        string dn = "שם התרופה: " + d.Name;


                    }

                    @Html.DisplayFor(modelItem => StartDate)
                    <br>
                    @Html.DisplayFor(modelItem => EndDate)
                    <br>
                    @Html.DisplayFor(modelItem => docname)
                    <br>
                    <b>פרטי המטופל:</b>
                    <br>
                    @Html.DisplayFor(modelItem => FirstName)
                    &nbsp;&nbsp;&nbsp;&nbsp;
                    @Html.DisplayFor(modelItem => LastName)
                    <br>
                    @Html.DisplayFor(modelItem => idcust)
                    <br>

                    @Html.DisplayFor(modelItem => dn)
                </div>


            }
        </div>
    </div>

    <script src="/js/jquery-3.2.1.min.js"></script>
    <script src="/styles/bootstrap4/popper.js"></script>
    <script src="/styles/bootstrap4/bootstrap.min.js"></script>
    <script src="/plugins/easing/easing.js"></script>
    <script src="/plugins/parallax-js-master/parallax.min.js"></script>
    <script src="/js/services.js"></script>
</body>
</html>